# ML Pipeline Preparation
Follow the instructions below to help you create your ML pipeline.
### 1. Import libraries and load data from database.
- Import Python libraries
- Load dataset from database with [`read_sql_table`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html)
- Define feature and target variables X and Y

In [1]:
# import libraries
import pandas as pd
from sqlalchemy import create_engine
import re
import numpy as np

import nltk
#nltk.download(['punkt', 'wordnet'])
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

# load data from database
engine = create_engine('sqlite:///../data/DisasterResponse.db')
df = pd.read_sql("SELECT * FROM DisasterResponse", engine)
df.head()

OperationalError: (sqlite3.OperationalError) no such table: DisasterResponse
[SQL: SELECT * FROM DisasterResponse]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [ ]:
df[df['related'] > 1]

In [ ]:
X = df['message'].values
category_names = ['related', 'request', 'offer',
       'aid_related', 'medical_help', 'medical_products', 'search_and_rescue',
       'security', 'military', 'child_alone', 'water', 'food', 'shelter',
       'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid',
       'infrastructure_related', 'transport', 'buildings', 'electricity',
       'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure',
       'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold',
       'other_weather', 'direct_report']
y = df[category_names].values

In [ ]:
X

In [111]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [112]:
y.shape

(26216, 36)

### 2. Write a tokenization function to process your text data

In [71]:
def tokenize(text):

    # clean text - remove special characters, normalize case 
    text = re.sub(r"[^a-zA-Z0-9]", " ", text).lower()
    
    # tokenize text
    tokens = nltk.word_tokenize(text)
    
    # remove stop words
    tokens = [w for w in tokens if w not in stopwords.words("english")]
    
    # initiate lemmatizer
    lemmatizer = WordNetLemmatizer()

    # lemmatize each token
    clean_tokens = [lemmatizer.lemmatize(tok) for tok in tokens]
    
    return clean_tokens

In [72]:
tokenize(X[0]), tokenize(X[1]), tokenize(X[2]), tokenize(X[3])

(['weather', 'update', 'cold', 'front', 'cuba', 'could', 'pas', 'haiti'],
 ['hurricane'],
 ['looking', 'someone', 'name'],
 ['un',
  'report',
  'leogane',
  '80',
  '90',
  'destroyed',
  'hospital',
  'st',
  'croix',
  'functioning',
  'need',
  'supply',
  'desperately'])

### 3. Build a machine learning pipeline
This machine pipeline should take in the `message` column as input and output classification results on the other 36 categories in the dataset. You may find the [MultiOutputClassifier](http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputClassifier.html) helpful for predicting multiple target variables.

In [86]:
pipeline = Pipeline([
    ('vect', CountVectorizer(tokenizer = tokenize)),
    ('tfidf', TfidfTransformer()),
    ('clf', MultiOutputClassifier(RandomForestClassifier())),
])

### 4. Train pipeline
- Split data into train and test sets
- Train pipeline

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [88]:
# train classifier
pipeline.fit(X_train, y_train)
# predict on test data
y_pred = pipeline.predict(X_test)

### 5. Test your model
Report the f1 score, precision and recall for each output category of the dataset. You can do this by iterating through the columns and calling sklearn's `classification_report` on each.

In [107]:
y_pred

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [113]:
y_test

array([[1, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [114]:
y_pred[:,0]

array([1, 1, 1, ..., 1, 1, 0])

In [120]:
for i, cat in enumerate(category_names):
    print('Classification report for {}: \n {}'.format(cat, classification_report(y_test[:,i], y_pred[:,i])))

Classification report for related: 
               precision    recall  f1-score   support

           0       0.72      0.43      0.54      1573
           1       0.84      0.94      0.89      4944
           2       0.29      0.43      0.35        37

    accuracy                           0.82      6554
   macro avg       0.62      0.60      0.59      6554
weighted avg       0.81      0.82      0.80      6554

Classification report for request: 
               precision    recall  f1-score   support

           0       0.90      0.98      0.94      5458
           1       0.80      0.48      0.60      1096

    accuracy                           0.89      6554
   macro avg       0.85      0.73      0.77      6554
weighted avg       0.89      0.89      0.88      6554

Classification report for offer: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      6522
           1       0.00      0.00      0.00        32

    accuracy       

Classification report for other_weather: 
               precision    recall  f1-score   support

           0       0.95      1.00      0.97      6212
           1       0.41      0.03      0.05       342

    accuracy                           0.95      6554
   macro avg       0.68      0.51      0.51      6554
weighted avg       0.92      0.95      0.92      6554

Classification report for direct_report: 
               precision    recall  f1-score   support

           0       0.87      0.97      0.92      5337
           1       0.75      0.36      0.49      1217

    accuracy                           0.86      6554
   macro avg       0.81      0.67      0.70      6554
weighted avg       0.85      0.86      0.84      6554



### 6. Improve your model
Use grid search to find better parameters. 

In [123]:
pipeline.get_params()

{'memory': None,
 'steps': [('vect',
   CountVectorizer(tokenizer=<function tokenize at 0x7fef3bc56700>)),
  ('tfidf', TfidfTransformer()),
  ('clf', MultiOutputClassifier(estimator=RandomForestClassifier()))],
 'verbose': False,
 'vect': CountVectorizer(tokenizer=<function tokenize at 0x7fef3bc56700>),
 'tfidf': TfidfTransformer(),
 'clf': MultiOutputClassifier(estimator=RandomForestClassifier()),
 'vect__analyzer': 'word',
 'vect__binary': False,
 'vect__decode_error': 'strict',
 'vect__dtype': numpy.int64,
 'vect__encoding': 'utf-8',
 'vect__input': 'content',
 'vect__lowercase': True,
 'vect__max_df': 1.0,
 'vect__max_features': None,
 'vect__min_df': 1,
 'vect__ngram_range': (1, 1),
 'vect__preprocessor': None,
 'vect__stop_words': None,
 'vect__strip_accents': None,
 'vect__token_pattern': '(?u)\\b\\w\\w+\\b',
 'vect__tokenizer': <function __main__.tokenize(text)>,
 'vect__vocabulary': None,
 'tfidf__norm': 'l2',
 'tfidf__smooth_idf': True,
 'tfidf__sublinear_tf': False,
 'tfidf_

In [127]:
parameters = {
    'vect__stop_words': [None, 'english'],
    'clf__estimator__criterion': ['gini', 'entropy']
}

# create grid search object
cv = GridSearchCV(pipeline, param_grid=parameters)

In [128]:
cv

GridSearchCV(estimator=Pipeline(steps=[('vect',
                                        CountVectorizer(tokenizer=<function tokenize at 0x7fef3bc56700>)),
                                       ('tfidf', TfidfTransformer()),
                                       ('clf',
                                        MultiOutputClassifier(estimator=RandomForestClassifier()))]),
             param_grid={'clf__estimator__criterion': ['gini', 'entropy'],
                         'vect__stop_words': [None, 'english']})

### 7. Test your model
Show the accuracy, precision, and recall of the tuned model.  

Since this project focuses on code quality, process, and  pipelines, there is no minimum performance metric needed to pass. However, make sure to fine tune your models for accuracy, precision and recall to make your project stand out - especially for your portfolio!

In [ ]:
cv.fit(X_train, y_train)
y_pred = cv.predict(X_test)
    


In [ ]:
cv.best_params_

### 8. Try improving your model further. Here are a few ideas:
* try other machine learning algorithms
* add other features besides the TF-IDF

### 9. Export your model as a pickle file

In [121]:
import pickle

filename = 'model.sav'
pickle.dump(pipeline, open(filename, 'wb'))

### 10. Use this notebook to complete `train.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database and export a model based on a new dataset specified by the user.